apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Chart.AppVersion }}
  labels:
    version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      app: frontend
      version: {{ .Chart.AppVersion }}
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Chart.AppVersion }}
    spec:
      containers:
      - name: frontend
        image: registry.cn-shanghai.aliyuncs.com/zjn-test-ns/frontend:{{ .Values.imageVersion }}
      imagePullSecrets:
      - name: regcred
---
apiVersion: {{ .Chart.AppVersion }}
kind: Service
metadata:
  name: frontend-svc
  labels:
    version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
  - name: frontend-port
    port: 80
    targetPort: 80
  selector:
    app: frontend
    version: {{ .Chart.AppVersion }}

