apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  labels:
    version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Chart.AppVersion }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.registry }}/frontend:{{ .Values.imageVersion }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: frontend-es-cred
        readinessProbe:
          httpGet:
            path: /
            port: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
  - name: frontend-port
    port: 80
    targetPort: 80
  selector:
    app: frontend

