apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
data:
  secretkey: R2RtS0RjSS8yRWF0eDI5MWhPOHBnb0pJcE5ZT3dtSC90NWdBdDhJa3Y0bW41MjFZM1NNMDAwRzduYm12WEFXMwpHWVlqU1FkeXArcUMwU25iUzI1Mjh0RDJrMHZTWmEvcDVaT3kyWVA5M3hCVVdvQVJZK2xIcncrdVhCV21BWmlMCmNsS1dDTEl3em84YjFuTlZSVnFGRWhqSm14UkErbVdoU1VWcVE2Sm9IcHc9